title : ACE Operations Professional and Operations (Bell)
author: Aviatrix ACE
copyright: '2024'
logo: '../docs/_logos/aviatrix-logo.png'

# Short description about the book
description: >-
  Aviatrix ACE Operations Professional and Operations (Bell) Lab Guides
execute:
  execute_notebooks           : off

# HTML-specific settings
html:
  home_page_in_navbar         : true
  favicon                     : '../docs/_logos/aviatrix-favicon-32.png'
