title: Aviatrix Automation - Instruqt Self Service
author: Aviatrix ACE
copyright: "2025"
logo: _static/Aviatrix_Logo_White_Gradient_RGB.svg

# Short description about the book
description: >-
  Aviatrix ACE Automation Lab Guide

execute:
  execute_notebooks: off

# HTML-specific settings
html:
  home_page_in_navbar: true
  favicon: "../docs/_logos/aviatrix-favicon-32.png"
  extra_css:
    - _static/custom.css
