title : Aviatrix Flight School - IaC
author: Aviatrix Flight School
copyright: '2023'
logo: '../docs/_logos/aviatrix-logo.png'

# Short description about the book
description: >-
  Aviatrix Flight School Infrastructure as Code Lab Guide

execute:
  execute_notebooks           : off

# HTML-specific settings
html:
  home_page_in_navbar         : true
  favicon                     : '../docs/_logos/aviatrix-favicon-32.png'
