name: PR File Check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: verify-version
        uses: actions-cool/verify-files-modify@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          forbid-files: "docs/index.html, docs/home.md, requirements.txt, CNAME, LICENSE"
          forbid-paths: "docs/_logos/, dist/"
          comment: |
            Please don't modify this.
          close: false
