name: PR File Check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: File Changed Check
        uses: danieljimeneznz/ensure-files-changed@v4.1.1
        with:
          # A list of files (or glob patterns) that represent the files that should not be modified by a PR.
          prevent-changes-to: |
            LICENSE.md
            docs/_logos
            docs/index.html
            docs/CNAME
            docs/home.md
            reqirements.txt
          # The GitHub token used to create an authenticated client.
          token: ${{ secrets.GITHUB_TOKEN }}
