name: PR File Check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # Checkout is required before did-files-change
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # be sure to override the default value (1) for fetch-depth

      - name: Check changes
        id: check-changes
        uses: rdietrick/did-files-change@v1.3.3
        with:
          pathspec: requirements.txt

      - name: Debug
        run: |
          echo "Changes detected in test directory: ${{ steps.check-changes.outputs.changed }}"
