name: PR File Check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR for modified files
      id: pr_files
      uses: actions/checkout@v2

    - name: List modified files
      run: echo ::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

    - name: Check for requirements.txt file changes
      id: check_requirements_txt
      run: |
        files="$((echo ${{ steps.pr_files.outputs.files }}))"
        if [[ $files == *"requirements.txt"* ]]; then
          echo "ERROR: The 'main.go' file was modified. Please remove or update it in a separate PR."
          exit 1
        fi

    - name: Approve PR
      if: success() && steps.check_main_go.outcome == 'success'
      run: echo "PR is approved!"

    - name: Disapprove PR
      if: failure() || steps.check_main_go.outcome == 'failure'
      run: echo "PR is not approved. Check the error message for details."
