name: PR File Check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Immutable Files
        uses: asafHalely/immutable-file-action@v1
        with:
          files: images
            requirements.txt
            CNAME
            docs/home.md
            docs/index.html
            docs/_images
